### ISSUE TITLE
Change to a person-centric data model

### ISSUE THREAD

**Issue by brylie** [brylie/companionship-care#16]
Our data model currently defines a `Group` model, which represents a care group for a particular person. Rather than the `Group` model being the primary entity, it would align more with our conceptual model and vision to have a `Person` model be the central entity.

## Task

- [ ] Replace the `Group` model with a `Person` model
- [ ] Replace the `Member` model with a `Companion` model
- [ ] ensure all functionality still works with the `Person` model
- [ ] ensure UI texts are updated to reflect the person-centric nature of the application
